"""Capture-strategy implementations and source-family guardrail contracts."""

from .api import (
    APICaptureError,
    APICaptureEvidence,
    APICaptureWindow,
    APIPageEvidence,
    APIPaginationPolicy,
    assert_same_api_window,
    freeze_api_window,
    validate_api_capture,
)
from .bootstrap_cdc import (
    CDCBootstrapEvidence,
    CDCBootstrapEvidenceError,
    CDCBootstrapPlan,
    normalize_bootstrap_cdc_batch,
    plan_cdc_bootstrap,
)
from .cdc import (
    CDCCheckpoint,
    CDCCheckpointTransition,
    CDCConflictError,
    CDCContractError,
    CDCEvidenceError,
    CDCEvent,
    CDCNormalizedBatch,
    CDCOperation,
    CDCOrderingError,
    CDCSourcePosition,
    build_cdc_checkpoint,
    normalize_cdc_batch,
)
from .files import (
    FileManifestError,
    FileManifestPolicy,
    FileObjectEvidence,
    FileReadiness,
    FrozenFileManifest,
    assert_same_file_manifest,
    freeze_file_manifest,
)
from .full import (
    FullCaptureBatch,
    FullSnapshotEvidence,
    FullSnapshotEvidenceError,
    capture_full_snapshot,
)
from .snapshot import (
    SnapshotCaptureBatch,
    SnapshotEvidence,
    SnapshotEvidenceError,
    capture_snapshot,
)

__all__ = [
    "APICaptureError",
    "APICaptureEvidence",
    "APICaptureWindow",
    "APIPageEvidence",
    "APIPaginationPolicy",
    "CDCBootstrapEvidence",
    "CDCBootstrapEvidenceError",
    "CDCBootstrapPlan",
    "CDCCheckpoint",
    "CDCCheckpointTransition",
    "CDCConflictError",
    "CDCContractError",
    "CDCEvidenceError",
    "CDCEvent",
    "CDCNormalizedBatch",
    "CDCOperation",
    "CDCOrderingError",
    "CDCSourcePosition",
    "FileManifestError",
    "FileManifestPolicy",
    "FileObjectEvidence",
    "FileReadiness",
    "FrozenFileManifest",
    "FullCaptureBatch",
    "FullSnapshotEvidence",
    "FullSnapshotEvidenceError",
    "SnapshotCaptureBatch",
    "SnapshotEvidence",
    "SnapshotEvidenceError",
    "assert_same_api_window",
    "assert_same_file_manifest",
    "build_cdc_checkpoint",
    "capture_full_snapshot",
    "capture_snapshot",
    "freeze_api_window",
    "freeze_file_manifest",
    "normalize_bootstrap_cdc_batch",
    "normalize_cdc_batch",
    "plan_cdc_bootstrap",
    "validate_api_capture",
]
