"""Reusable contracts for the enterprise Microsoft Fabric data framework."""

from .apply.append import (
    AppendApplyResult,
    AppendConflictError,
    AppendIdentityError,
    InMemoryAppendTarget,
    apply_append,
)
from .apply.replace import ReplaceGuardPolicy
from .apply.scd1 import (
    SCD1ApplyPolicy,
    SCD1ApplyResult,
    SCD1ConflictError,
    SCD1OrderingError,
    StaleRecordAction,
    apply_scd1,
)
from .apply.snapshot_diff import SnapshotDiffPolicy
from .apply.upsert import (
    UpsertApplyPolicy,
    UpsertApplyResult,
    UpsertConflictError,
    UpsertOrderingError,
    apply_upsert,
)
from .capture import (
    APICaptureError,
    APICaptureEvidence,
    APICaptureWindow,
    APIPageEvidence,
    APIPaginationPolicy,
    FileManifestError,
    FileManifestPolicy,
    FileObjectEvidence,
    FileReadiness,
    FrozenFileManifest,
    FullSnapshotEvidence,
    SnapshotEvidence,
    assert_same_api_window,
    assert_same_file_manifest,
    freeze_api_window,
    freeze_file_manifest,
    validate_api_capture,
)
from .config import (
    ApplyStrategy,
    CaptureStrategy,
    Criticality,
    DataQualityPolicy,
    DatasetConfig,
    DatasetStatus,
    EffectiveDatasetConfig,
    ExecutionEngine,
    ExecutionPolicy,
    ExtensionConfig,
    LoadPolicy,
    OrchestrationPolicy,
    OverrideField,
    PipelineStatus,
    ProgressOwner,
    ReconciliationPolicy,
    RunMode,
    RuntimeOverride,
    SourceConfig,
    TargetConfig,
    WatermarkConfig,
    resolve_effective_config,
)
from .contracts import (
    CaptureReceipt,
    ExecutionKind,
    ExecutionPlan,
    ExecutionRole,
    ExecutionUnit,
    build_default_execution_plan,
    compile_execution_plan,
)
from .dispatcher import (
    DatasetDispatchOutcome,
    DatasetDispatchRequest,
    OrchestrationIntegrityError,
    PipelineDispatchResult,
    dispatch_datasets,
)
from .execution import execute_append_batch, execute_full_replace, execute_snapshot_diff
from .extensions import ExtensionKind, ExtensionRegistry
from .metadata import CapabilityRegistry, UnsupportedExecutionCombination
from .quality import (
    SchemaChangeKind,
    SchemaEvolutionClassification,
    SchemaEvolutionDecision,
    classify_schema_evolution,
    require_compatible_schema,
)
from .schema_contract import (
    LogicalType,
    SchemaCompatibilityPolicy,
    SchemaContract,
    SchemaField,
    SchemaShape,
)

__all__ = [
    "APICaptureError",
    "APICaptureEvidence",
    "APICaptureWindow",
    "APIPageEvidence",
    "APIPaginationPolicy",
    "AppendApplyResult",
    "AppendConflictError",
    "AppendIdentityError",
    "ApplyStrategy",
    "CapabilityRegistry",
    "CaptureReceipt",
    "CaptureStrategy",
    "Criticality",
    "DataQualityPolicy",
    "DatasetConfig",
    "DatasetDispatchOutcome",
    "DatasetDispatchRequest",
    "DatasetStatus",
    "EffectiveDatasetConfig",
    "ExecutionEngine",
    "ExecutionKind",
    "ExecutionPlan",
    "ExecutionPolicy",
    "ExecutionRole",
    "ExecutionUnit",
    "ExtensionConfig",
    "ExtensionKind",
    "ExtensionRegistry",
    "FileManifestError",
    "FileManifestPolicy",
    "FileObjectEvidence",
    "FileReadiness",
    "FrozenFileManifest",
    "FullSnapshotEvidence",
    "InMemoryAppendTarget",
    "LoadPolicy",
    "LogicalType",
    "OrchestrationIntegrityError",
    "OrchestrationPolicy",
    "OverrideField",
    "PipelineDispatchResult",
    "PipelineStatus",
    "ProgressOwner",
    "ReconciliationPolicy",
    "ReplaceGuardPolicy",
    "RunMode",
    "RuntimeOverride",
    "SCD1ApplyPolicy",
    "SCD1ApplyResult",
    "SCD1ConflictError",
    "SCD1OrderingError",
    "SchemaChangeKind",
    "SchemaCompatibilityPolicy",
    "SchemaContract",
    "SchemaEvolutionClassification",
    "SchemaEvolutionDecision",
    "SchemaField",
    "SchemaShape",
    "SnapshotDiffPolicy",
    "SnapshotEvidence",
    "SourceConfig",
    "StaleRecordAction",
    "TargetConfig",
    "UnsupportedExecutionCombination",
    "UpsertApplyPolicy",
    "UpsertApplyResult",
    "UpsertConflictError",
    "UpsertOrderingError",
    "WatermarkConfig",
    "apply_append",
    "apply_scd1",
    "apply_upsert",
    "assert_same_api_window",
    "assert_same_file_manifest",
    "build_default_execution_plan",
    "classify_schema_evolution",
    "compile_execution_plan",
    "dispatch_datasets",
    "execute_append_batch",
    "execute_full_replace",
    "execute_snapshot_diff",
    "freeze_api_window",
    "freeze_file_manifest",
    "require_compatible_schema",
    "resolve_effective_config",
    "validate_api_capture",
]

__version__ = "0.4.0"
