"""Apply-strategy implementations and publication guards."""

from .append import (
    APPEND_IDENTITY_HASH,
    APPEND_PAYLOAD_HASH,
    AppendApplyError,
    AppendApplyResult,
    AppendConflictError,
    AppendIdentityError,
    InMemoryAppendTarget,
    apply_append,
)
from .cdc import (
    CDCApplyError,
    CDCCurrentStateApplyResult,
    CDCDeleteAction,
    CDCDeleteRejectedError,
    CDC_PARTITION,
    CDC_POSITION,
    apply_cdc_current_state,
)
from .cdc_scd2 import (
    CDC_CLOSED_PARTITION,
    CDC_CLOSED_POSITION,
    CDCSCD2ApplyResult,
    CDCSCD2ConflictError,
    CDCSCD2Error,
    CDCSCD2LateArrivingError,
    apply_cdc_scd2,
)
from .replace import (
    InMemoryReplaceTarget,
    ReplaceGuardError,
    ReplaceGuardPolicy,
    ReplacePlan,
    plan_replace,
)
from .scd1 import (
    InMemorySCD1Target,
    SCD1ApplyPolicy,
    SCD1ApplyResult,
    SCD1ConflictError,
    SCD1OrderingError,
    StaleRecordAction,
    apply_scd1,
)
from .snapshot_diff import (
    SnapshotDiffError,
    SnapshotDiffPlan,
    SnapshotDiffPolicy,
    plan_snapshot_diff,
)
from .upsert import (
    InMemoryUpsertTarget,
    UpsertApplyPolicy,
    UpsertApplyResult,
    UpsertConflictError,
    UpsertOrderingError,
    apply_upsert,
)

__all__ = [
    "APPEND_IDENTITY_HASH",
    "APPEND_PAYLOAD_HASH",
    "AppendApplyError",
    "AppendApplyResult",
    "AppendConflictError",
    "AppendIdentityError",
    "CDCApplyError",
    "CDCDeleteAction",
    "CDCDeleteRejectedError",
    "CDCCurrentStateApplyResult",
    "CDCSCD2ApplyResult",
    "CDCSCD2ConflictError",
    "CDCSCD2Error",
    "CDCSCD2LateArrivingError",
    "CDC_CLOSED_PARTITION",
    "CDC_CLOSED_POSITION",
    "CDC_PARTITION",
    "CDC_POSITION",
    "InMemoryAppendTarget",
    "InMemoryReplaceTarget",
    "InMemorySCD1Target",
    "InMemoryUpsertTarget",
    "ReplaceGuardError",
    "ReplaceGuardPolicy",
    "ReplacePlan",
    "SCD1ApplyPolicy",
    "SCD1ApplyResult",
    "SCD1ConflictError",
    "SCD1OrderingError",
    "SnapshotDiffError",
    "SnapshotDiffPlan",
    "SnapshotDiffPolicy",
    "StaleRecordAction",
    "UpsertApplyPolicy",
    "UpsertApplyResult",
    "UpsertConflictError",
    "UpsertOrderingError",
    "apply_append",
    "apply_cdc_current_state",
    "apply_cdc_scd2",
    "apply_scd1",
    "apply_upsert",
    "plan_replace",
    "plan_snapshot_diff",
]
