"""Recovery, retry and reprocessing runtime."""

from .rebuild import (
    FullRebuildContext,
    FullRebuildError,
    FullRebuildGateError,
    FullRebuildMutationOutcome,
    FullRebuildResult,
    FullRebuildStateVersionConflict,
    InMemoryFullRebuildStateAdapter,
    execute_full_rebuild,
    prepare_full_rebuild,
)
from .replay import (
    PreparedQuarantineReplay,
    QuarantineReplayError,
    QuarantineReplayGateError,
    QuarantineReplayMutationOutcome,
    QuarantineReplayPayloadError,
    QuarantineReplayResult,
    execute_quarantine_replay,
    prepare_quarantine_replay,
)
from .runtime import (
    AttemptContext,
    FailureClassification,
    FailureDisposition,
    PermanentExecutionError,
    RecoveryExhaustedError,
    RecoveryRunResult,
    RetryPolicy,
    RetryableExecutionError,
    UnknownCommitOutcomeError,
    UnknownOutcomeUnresolvedError,
    classify_failure,
    execute_with_retry,
)
from .target_operation import (
    TargetOperationExecutionResult,
    TargetOperationJournal,
    TargetOperationTerminalError,
    TargetOperationUnresolvedError,
    execute_target_operation_once,
    execute_target_operation_with_retry,
)

__all__ = [
    "AttemptContext",
    "FailureClassification",
    "FailureDisposition",
    "FullRebuildContext",
    "FullRebuildError",
    "FullRebuildGateError",
    "FullRebuildMutationOutcome",
    "FullRebuildResult",
    "FullRebuildStateVersionConflict",
    "InMemoryFullRebuildStateAdapter",
    "PermanentExecutionError",
    "PreparedQuarantineReplay",
    "QuarantineReplayError",
    "QuarantineReplayGateError",
    "QuarantineReplayMutationOutcome",
    "QuarantineReplayPayloadError",
    "QuarantineReplayResult",
    "RecoveryExhaustedError",
    "RecoveryRunResult",
    "RetryPolicy",
    "RetryableExecutionError",
    "TargetOperationExecutionResult",
    "TargetOperationJournal",
    "TargetOperationTerminalError",
    "TargetOperationUnresolvedError",
    "UnknownCommitOutcomeError",
    "UnknownOutcomeUnresolvedError",
    "classify_failure",
    "execute_full_rebuild",
    "execute_quarantine_replay",
    "execute_target_operation_once",
    "execute_target_operation_with_retry",
    "execute_with_retry",
    "prepare_full_rebuild",
    "prepare_quarantine_replay",
]
